pipeline{
	agent any

    parameters{
        choice("STATUS" , choices: ["Start","Stop"] )
    }
	stages{
		stage('Start Flyte Cluster'){
			steps{
                script{
                    if({env.STATUS=="Start"})
                        bat 'flytectl demo start'
                    else
                        bat 'flytectl demo stop'
                }
				
			}
		}
	}
}