pipeline {
   agent any
    environment {
      RELEASE='1.0.0'
      PROJECT_NAME='cancer-project'
    }
   stages {
      stage('Audit tools') {
         steps{
            auditTools()
         }
      }
      stage('Build') {
            environment {
               MLRUN_DBPATH='http://192.168.56.1:8080'
            }
            agent {
                docker {
                    image 'mlrun/jupyter:1.3.0'
                }
            }
            steps {
               echo "Building release ${RELEASE} for project ${PROJECT_NAME}..."
               sh 'chmod +x ./MLRun/build.sh'
               sh './MLRun/build.sh'
            }
        }
        stage('Test') {
            steps {
               echo "Testing release ${RELEASE}"
            }
        }
   }
}

void auditTools() {
   sh '''
      git version
      docker version
   '''
}